//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedScooby.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedScooby.Common.Resources.CommonStrings", typeof(CommonStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string _TextFlowDirection {
            get {
                return ResourceManager.GetString("_TextFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your friends, family and loved ones safe..
        /// </summary>
        public static string AppShortDescription {
            get {
                return ResourceManager.GetString("AppShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedScooby.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you&apos;re concerned and you&apos;d like your inner-circle to know, and keep track..
        /// </summary>
        public static string ConcernButtonDescription {
            get {
                return ResourceManager.GetString("ConcernButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m concerned..
        /// </summary>
        public static string ConcernButtonTitle {
            get {
                return ResourceManager.GetString("ConcernButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll keep checking in with you when the above timer expires..
        /// </summary>
        public static string ConcernModeInfo {
            get {
                return ResourceManager.GetString("ConcernModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll keep checking in with you. No one is alterted unless you fail to enter your PIN..
        /// </summary>
        public static string ConcernPrecautionOnButtonDescription {
            get {
                return ResourceManager.GetString("ConcernPrecautionOnButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be precautious..
        /// </summary>
        public static string ConcernPrecautionOnButtonTitle {
            get {
                return ResourceManager.GetString("ConcernPrecautionOnButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining estimated address...
        /// </summary>
        public static string DeterminingLocation {
            get {
                return ResourceManager.GetString("DeterminingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your closest circles and nearby professionals will be notified and can to track you in realtime. .
        /// </summary>
        public static string DistressOnButtonDescription1 {
            get {
                return ResourceManager.GetString("DistressOnButtonDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap and hold.
        /// </summary>
        public static string DistressOnButtonDescription2 {
            get {
                return ResourceManager.GetString("DistressOnButtonDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to make your entire screen into a lift-off trigger..
        /// </summary>
        public static string DistressOnButtonDescription3 {
            get {
                return ResourceManager.GetString("DistressOnButtonDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need help immediately..
        /// </summary>
        public static string DistressOnButtonTitle {
            get {
                return ResourceManager.GetString("DistressOnButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the first 3-digits of your PIN, or a distress be will triggered in {0} seconds..
        /// </summary>
        public static string PinModeConcernFeedback {
            get {
                return ResourceManager.GetString("PinModeConcernFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your 4-digit PIN to turn off concern mode. You have {0} seconds..
        /// </summary>
        public static string PinModeConcernOff {
            get {
                return ResourceManager.GetString("PinModeConcernOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your 4-digit PIN to cancel the distress call. You have {0} seconds..
        /// </summary>
        public static string PinModeDistressCancel {
            get {
                return ResourceManager.GetString("PinModeDistressCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your 4-digit PIN to turn off the distress call, and notify everyone you&apos;re safe..
        /// </summary>
        public static string PinModeDistressOff {
            get {
                return ResourceManager.GetString("PinModeDistressOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your PIN.
        /// </summary>
        public static string PinModeHeader {
            get {
                return ResourceManager.GetString("PinModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position not available..
        /// </summary>
        public static string PositionUnavailable {
            get {
                return ResourceManager.GetString("PositionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, 
        ///
        ///I&apos;ve just started using RedScooby. Its a new approach to personal security, combining the social factor into security and emphasizes on engaging the community to protect its people. I&apos;d like to add you to my circles. Please take a look at it here: {0}
        ///
        ///Cheers,
        ///{1}.
        /// </summary>
        public static string ShareEmailMessage {
            get {
                return ResourceManager.GetString("ShareEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve started using the RedScooby app, and would like to add you to my circles. Check it out: {0}.
        /// </summary>
        public static string ShareShortMessage {
            get {
                return ResourceManager.GetString("ShareShortMessage", resourceCulture);
            }
        }
    }
}
